### ISSUE TITLE
Bug - View page source tab is seen as a duplicate

### ISSUE THREAD

**Issue by olfek** [Peuj/duplicate-tabs-closer#13]
Steps to reproduce:

1. Set `On duplicate tab detected` to `Close tab automatically`
1. Set `On remaining tab` to `Activate`
1. Go to `www.google.com`
1. Right click
1. Click `View page source`
1. Observe that the 'view page source' tab is closed immediately as it is seen as a duplicate.

**Comment by Peuj** [comment]
Thanks for the clear report.
You just forget to specify the browser :) (it only happens with Chrome).
I will push a fix soon.

**Comment by olfek** [comment]
@Peuj Thank you

**Comment by Peuj** [comment]
Fix in 3.3.2
