### ISSUE TITLE
Unable to close duplicates in Firefox private windows

### ISSUE THREAD

**Issue by awsr** [Peuj/duplicate-tabs-closer#14]
Since the update from version 3.2.0 to 3.3.0, the list of duplicate tabs no longer works for private windows in Firefox. (Tested with Firefox 66.0.3 on Windows)

The icon still correctly shows the number of duplicate tabs, but when clicking on it the list that shows the duplicate tabs remains empty and "close all duplicate tabs" can't be clicked on. There are no issues with using the extension in a regular Firefox window.

When bringing up the extension in a private window, the browser console shows the following error:
`Error: Invalid contextual identity: firefox-private ExtensionUtils.jsm`

**Comment by awsr** [comment]
Using the hotkey combination to close all duplicate tabs does still work in a private window.

**Comment by Peuj** [comment]
Thanks for the report.
I've identified and fixed the problem.
I'll push a new release soon.

**Comment by Peuj** [comment]
Fix in 3.3.2
