### ISSUE TITLE
How does one use the white list?

### ISSUE THREAD

**Issue by businessBoris** [Peuj/duplicate-tabs-closer#16]
How does one use the white list?
- wildcards?
- http(s):// needed?
- regex?
- comma/semicolon/newline separated?

AFAICT entries need to be exact character-for-character matched: 
existing tab: https://www.bbc.co.uk/
Unless the whitelist contains "https://www.bbc.co.uk/" the duplicate is deleted. Even using http:// not https:// causes a deletion.

It's not actually very useful as is.

**Comment by Peuj** [comment]
- wildcards? **yes**
- http(s):// needed? **use wildcards or regex**
- regex? **yes**
- comma/semicolon/newline separated? **newline**

If the whitelist contains https://www.bbc.co.uk/ then only the url exactly matching https://www.bbc.co.uk/ will be skipped.  
If the you want to skip https://www.bbc.co.uk/  and http://www.bbc.co.uk/  then you need to add in the witelist something like `(http[s]?)://www.bbc.co.uk/ `or `(http|https)://www.bbc.co.uk/`

**Comment by businessBoris** [comment]
That's much better than I expected.
Are there any predicates on the other options? Once the URL matches a whitelist member the tab is no longer considered by the add-on, right?
Wish I could read the code a little better; practice needed here!

**Comment by Peuj** [comment]
I've updated the readme.  
If a tab is skipped because of the whitelist, it will be notified in the badge.

**Comment by businessBoris** [comment]
That's much better than I expected.
Are there any predicates on the other options? Once the URL matches a whitelist member the tab is no longer considered by the add-on, right?
Wish I could read the code a little better; practice needed here!

**Comment by businessBoris** [comment]
Sorry to re-open: 
If I want to capture https and http://bbc.co.uk, I should only need bbc.co.uk in the whitelist, right?
The regex should match without stating http(s):// , unless bizarrely "bbc\.co\.uk" occurs in the file path of the url?

Do I need delimiters for each regex (eg. "/regex/" ) and to escape the special characters ( \. not . ) ?

**Comment by Peuj** [comment]
You miss some information about how it works in the background.  

The idea with the the white list is to have an **exact** match.  
Also I don't want to have to use regexp so I write is what I want to skip.
By default a regexp is created starting with `^` and ending with `$`.
The wildcard caracter is replaced by `.*`

1- If you add in the whitelist the url http://www.bbc.co.uk/  
It will **only** skip http://www.bbc.co.uk/
But **not** https://www.bbc.co.uk/ or http://www.bbc.co.uk/something

2- If you want to skip urls `starting` with http://www.bbc.co.uk/  
Add in the whitelist this url http://www.bbc.co.uk/* 
It will skip http://www.bbc.co.uk/ and http://www.bbc.co.uk/anything

3- If you want to skip urls `starting` with http://www.bbc.co.uk/  or https://www.bbc.co.uk/ 
Add in the whitelist this url http*://www.bbc.co.uk/*  
It will skip anything starting with http://www.bbc.co.uk/ or https://www.bbc.co.uk/

4- If you use the regexp `bbc\.co\.uk` you will only skip this exact url `bbc.co.uk`

**Comment by caheru** [comment]
May I add a question? I'd rather blacklist than whitelist the urls as I only have a small number of urls which are supposed to be deduplicated while all others shall remain unaffected. Is it possible to do this using not in regex?
