### ISSUE TITLE
Options do not persist

### ISSUE THREAD

**Issue by AxiosDeminence** [Peuj/duplicate-tabs-closer#20]
There is currently a bug with the add-on where all options of the add-on (e.g. duplicate tab behavior) do not persist and reset to the default options. Bug has been going on for the past couple of weeks on the most updated versions of the add-on (do not know the exact date it started nor the version that this issue started). Bug persists on multiple versions of Firefox (68.0.2 and 69.0). There are two ways to reproduce the issue.

1. Restart Firefox by closing all open windows.
2. Disable and then re-enable the add-on.

**Comment by Peuj** [comment]
Thanks for the report. I think I know where to search.

**Comment by Peuj** [comment]
Fix with version 3.4.1
