### ISSUE TITLE
Close duplicate tabs opened within a certain amount of time from each other

### ISSUE THREAD

**Issue by Matroc** [Peuj/duplicate-tabs-closer#23]
Let me explain my issue here. I have a laptop with a Synaptics touchpad that has a terrible driver. I had to do some registry hacks to even get it to do middleclicks at all. However, it randomly seems to send multiple middleclicks at once which results in multiple duplicate tabs being opened when i middleclick any link, which is rather annoying.

I would love to use this extension to "fix" my problem, but i often want to have multiple copies of the same page open in different trees of my tree style tabs. Would it be possible to implement a filter or scope to only automatically close tabs that were opened within x ms of each other?

**Comment by Peuj** [comment]
Sorry but for the moment this needs too much tricky work to implementthis.
