### ISSUE TITLE
"Duplicate tabs" pane in the popup panel doesn't work

### ISSUE THREAD

**Issue by fennelpollen** [Peuj/duplicate-tabs-closer#25]
I reported the same in Chrome Web Store a week ago. When I click the top-right icon (Duplicate Tabs Closer), then on the popup panel's "Duplicate tabs" pane is broken for some reason. Indeed, clicking on any window name does nothing. Absolutely nothing happens. When clicking the X there, the window title still stays in the pane. However, the top-right icon's number decreases by one so it works. The title should disappear from the list though, right?

In the chrome-extension://gnmdbogfankgjepgglmmfmbnimcmcjle/optionPage/optionPage.html page, clicking on a Duplcate tabs pane window title, it works as intended. And X works except it doesn't remove the window title until refreshing the page. Let me know if you need more details.

**Comment by Peuj** [comment]
First the popup only appears on left click, no with the right click.
What do you mean by broken? I expect that you see something like this:  

![image](https://user-images.githubusercontent.com/6862131/68246849-f43c5b00-0019-11ea-9e8f-5a63ed7336d0.png)

About the problem:
> Indeed, clicking on any window name does nothing. Absolutely nothing happens. When clicking the X there, the window title still stays in the pane. However, the top-right icon's number decreases by one so it works. The title should disappear from the list though, right?

> And X works except it doesn't remove the window title until refreshing the page.

Sorry but I don't understand the steps you describe, can you send a screenshot and/or describe differently?
