### ISSUE TITLE
High Priority: Prevents Google drive services to open new tab

### ISSUE THREAD

**Issue by ramlaxman** [Peuj/duplicate-tabs-closer#28]
Upon enabling duplicate tab closer, all google services based files are unable to open in new tab.
For ex. if I am opening google docs from google drive, new tab gets closed automatically.
If I want to open docs in new tab, I need to disable addon otherwise it works fine for others.

**Comment by Peuj** [comment]
Thanks for the report.
I can reproduce the problem, I'll investigate on it.

**Comment by Peuj** [comment]
The problem has been fix in version 3.5.2
