### ISSUE TITLE
Option to ignore case

### ISSUE THREAD

**Issue by josefGme** [Peuj/duplicate-tabs-closer#29]
Hello, could you add an option to ignore the case in the search part, so that for example `www.example.com/?s=pattern` will be seen as a duplicate of `www.example.com/?s=PATTERN`?

**Comment by Peuj** [comment]
To avoid to many filter options, I'll add an option to ignore the case for the complete URL

**Comment by josefGme** [comment]
Thank you.

**Comment by Peuj** [comment]
Done in version 3.5.0

**Comment by josefGme** [comment]
Thank you so much, works as expected.
