### ISSUE TITLE
Enlarge the badge

### ISSUE THREAD

**Issue by nollinvoyd** [Peuj/duplicate-tabs-closer#3]
I'd like to have option to increase the duplicate tab count font size or have it completely replace the toolbar button icon display when activated by duplicate tabs.

thanks

-----------------------------
Windows 10, Fx 63.09b

**Comment by Peuj** [comment]
There no API to modify the font size and replacing the icon with numbers means having all the images with the corresponding numbers. Not feasible for the moment.
