### ISSUE TITLE
How do i add the Homepage of firefox to the whitelist?

### ISSUE THREAD

**Issue by anthonym01** [Peuj/duplicate-tabs-closer#31]
Id very much like to know how to do this

**Comment by Peuj** [comment]
I don't know yet. It seems the default URL for the homepage is `about:newtab` so it's difficult to identify.
I'll make some tests

**Comment by anthonym01** [comment]
> about:newtab

Lol, i had a space between "new" and "tab"
"about:newtab" works in the whitelist XD

**Comment by strangeh** [comment]
But what should i add in whitelist if my new tab replaced by Quick Dial extension?..

**Comment by Peuj** [comment]
@strangeh I guess Quick Dial extension is https://addons.mozilla.org/en-US/firefox/addon/quick-dial/
You need to copy the url of the new tab, you should get something similar to `moz-extension://83f5c38a-166e-429d-9e56-11424778d061/dial`
