### ISSUE TITLE
Close popup panel after deleting duplicates

### ISSUE THREAD

**Issue by Gitoffthelawn** [Peuj/duplicate-tabs-closer#36]
After deleting duplicates, the extension's popup panel remains open.

It would be beneficial to close it after deleting duplicates (or at the least, make that an option).

**Comment by Peuj** [comment]
I'll add an option for this.

Personally I like it this way because I can use a filter, close the tabs then use another filter and close the tabs again.

**Comment by Gitoffthelawn** [comment]
Thanks for adding the option!

**Comment by Peuj** [comment]
Delivered in version 3.5.2:
New custom option to close popup panel after closing duplicate tabs

**Comment by Gitoffthelawn** [comment]
Thank you so much!
