### ISSUE TITLE
Not posible to hide options section in the panel

### ISSUE THREAD

**Issue by andreumasferrer** [Peuj/duplicate-tabs-closer#37]
Since the last update, it's not possible to hide the options section from the panel. Before It was possible to collapse it. It was handy to just focus on seeing the list of duplicate tabs. 
Browser: Chrome

**Comment by beerlion** [comment]
I support this. Another customization option like "Show only duplicate tabs list" would be great.

**Comment by Peuj** [comment]
Hello, I forget to add it back when I've updated the UI.
I'll add it in the new version I'm working on.

**Comment by Peuj** [comment]
Delivered in version 3.5.2:
* You can show/hide the 'Options' section.
* If all options are unpinned, when you open the popup, the 'Options' section is hidden.
* Added a new option to only show pinned options
