### ISSUE TITLE
FF version and Container

### ISSUE THREAD

**Issue by khabib227** [Peuj/duplicate-tabs-closer#39]
Please add ignore containers in filters, without it you can't use containers, and if possible re-add firefox 67 compatibility

thanks

**Comment by alexhk** [comment]
+1. 


@Peuj  Nevermind, I saw that this is already supported (I am new to Duplicate Tabs Closer), what a fantastic add-on!

- **Container in active window:** only closes/displays duplicate tabs that belong to a same container in the active window.
- **Container in all windows:** only closes/displays duplicate tabs that belong to a same container in all windows.
