### ISSUE TITLE
ver 3.5.2 and 3.5.3 doesn't work on 68.9.0esr

### ISSUE THREAD

**Issue by perdolka** [Peuj/duplicate-tabs-closer#40]
Delete button doesn't work.

**Comment by Peuj** [comment]
I've introduced the Resize Observer API which is supported since Firefox 69.
If I don't find a simple solution I'll probably remove the support for Firefox 68.

**Comment by perdolka** [comment]
Ok. 
3.5.1 works great.

**Comment by Peuj** [comment]
Yes 3.5.1 doesn't use the Resize Observer API :)
Just by curiosity why don't you simply use Firefox 69 ?

**Comment by perdolka** [comment]
It's just a habit of using ESR versions. :)

**Comment by Peuj** [comment]
As the latest ESR version is 78.9 and this version support the Resize Observer API, I close the bug.
Sorry I've missed time to work on this issue.
