### ISSUE TITLE
Firefox: manual close of duplicate tabs stopped working

### ISSUE THREAD

**Issue by concese** [Peuj/duplicate-tabs-closer#41]
OS: Windows 10 Enterprise
Browser: Firefox 68.9.0esr (64-bit)
Add-on version: 3.5.3

Steps to reproduce:
1. Open 2 or more tabs in the same page
2. It detects correctly the duplicate tabs and shows the number
3. Click on the the "close all" button does nothing
   Clicking on the individual "x" associated with tab, has the same result

I have also uninstalled, restarted FF and reinstalled the add-on. Same result. 
Should I need to clean some files before reinstall to make sure it's clean?

Thank you for the time invested - it's a very useful tool.

![image](https://user-images.githubusercontent.com/26224424/85054938-18aa0980-b19d-11ea-8c61-6b6f9db47165.png)

**Comment by concese** [comment]
It seems I didn't notice someone had also reported it before: https://github.com/Peuj/duplicate-tabs-closer/issues/40

**Comment by Peuj** [comment]
I confirm it's the same problem.
I close this duplicate issue.
Thanks for the report.
