### ISSUE TITLE
Closing stopped working from toolbar (v 3.5.3  on FF68.10.0esr)

### ISSUE THREAD

**Issue by EvieHeaven** [Peuj/duplicate-tabs-closer#43]
Originally, when I installed the plugin, it worked correctly. But after some update, "Close All" and clicking on X next to page link does not do anything when trying to do it from toolbar pop-up (it happened at the same time, when unpinning parts of popup became impossible). I now can unpin parts of popup from toolbar now, but Close All or single close, even opening the tab I am clicking in list still does not work from toolbar popup, but works from Options.

My rules are: False on "Ignore search part in URL" and "Ignore path part in URL", all others are set to True. Scope is All Windows. 

I get quite a bit duplicated tabs and usually prefer to clean them out several times a day, but I would like not to go to Options every time to do it.

**Comment by abcdenis** [comment]
Rollback to working version 3.5.0:
1) disable autoupdate for duplicate_tabs_closer in settings
2) uninstall it
3) download 3.5.0 from Mozilla: 
`curl https://addons.cdn.mozilla.net/user-media/addons/417674/duplicate_tabs_closer-3.5.0-fx.xpi -O`
4) install it from file 
5) check settings that autoupdate is still disabled
6) use toolbar button :)

**Comment by Peuj** [comment]
I don't have access to internet for the moment.
I'll check that in 2 weeks.

**Comment by Peuj** [comment]
Most probably same issue https://github.com/Peuj/duplicate-tabs-closer/issues/40

**Comment by EvieHeaven** [comment]
Hi,

Thanks for direct link to download. I clicked it accidentally before
uninstalling the non-working version, but it replaced immediately, so for
the moment it is working fine.

I will be waiting for working new version, but this one is back to saving
me from about 50 (+-) duplicate tabs everyday.

**Comment by Peuj** [comment]
See comments on issue #40
