### ISSUE TITLE
Can fix a invalid option bug🐞 ?

### ISSUE THREAD

**Issue by dnknn** [Peuj/duplicate-tabs-closer#44]
![Pic-200727_1039](https://user-images.githubusercontent.com/10995302/88498359-7f6cdf00-cff5-11ea-98af-08ca882121bd.png)When closeing tab automatically, `DTC` can't activate to Older_Duplicate_Tab .

[centbrowser.com](http://centbrowser.com/)&emsp;fork of Chromium⁸⁶ &emsp;

`chrome://settings/cbTabOptions#:~:text=Action after closing current tab`

The browser I use is `CentBrowser`, which also has `Action after closing current tab`, 

`DTC`(Duplicate-Tabs-Closer) can not working for `On remaining tab to Activate`,about this issue, 
### I think that is because `DTC` cannot overwrite same function of `CentBrowser` itself.

![Pic-200727_1034](https://user-images.githubusercontent.com/10995302/88498063-b55d9380-cff4-11ea-8bc4-3343b1f0ece4.png)

 
I have used too many extensions and haven't found that it can't overwrite the same function of the browser itself.
So, can you read the related **🔌API** documentation, for example, refer to this extension 👇
SimpleTabOrder [chrome.google.com/webstore/detail/cekafjbmkfofacenifehbglhmajimhjf](https://chrome.google.com/webstore/detail/cekafjbmkfofacenifehbglhmajimhjf)

![0727110009](https://user-images.githubusercontent.com/10995302/88499469-7b8e8c00-cff8-11ea-875f-b605f7bb415e.png)

- Is there an **API** that overwrite the same functions as the browser itself 👆,
> Because other extensions can all work perfectly.

**Comment by Peuj** [comment]
I don't have access to internet for the moment.
I'll check that in 2 weeks.
