### ISSUE TITLE
[Feature Request] URL Whitelist

### ISSUE THREAD

**Issue by afnkhn** [Peuj/duplicate-tabs-closer#5]
I don't want the extension to count my new tab pages. I am using Tabliss extension to override my new tab page so the URL of my new tab page is like this: moz-extension://<extension_id>/index.html.

**Comment by Peuj** [comment]
I'll add a whitelist feature, it should support your request

**Comment by Peuj** [comment]
Whitelist has been added in version 3.2.0

**Comment by businessBoris** [comment]
How do you use the white list?
- wildcards?
-http(s):// needed?
