### ISSUE TITLE
[Feature Request] Hide the badge if there is no duplicate tab

### ISSUE THREAD

**Issue by YandLiu** [Peuj/duplicate-tabs-closer#6]
The badge is too conspicuous when there is no duplicate tab, that makes the extension icon a little incongruous.

**Comment by Peuj** [comment]
The idea (the way I use it) is to be able to modify the options (mostly the filters) easily and quickly.
Anyway, I will see if I can add this new behavior easily.

**Comment by Keith94** [comment]
I support this.

**Comment by Peuj** [comment]
About my previous comment:
My concern is that if there is no badge visible you cannot access (and modify) the filters and you need to go to "Add-ons Manager" page which seems not convenient.

**Comment by Keith94** [comment]
What I expect is the toolbar button stays visible, but the badge element itself will not be displayed if the value reads zero (if there are no duplicate tabs). Otherwise, the badge is shown if one or more duplicates are present.

**Comment by Peuj** [comment]
Ok I get it. You want the same behavior than µBlock.
I'll do it.

**Comment by YandLiu** [comment]
Temporarily I'm using the following CSS code in userChrome.css
`#jid0-rvyt2rgwfm8q5ywxixahyaeo5qg_jetpack-browser-action .toolbarbutton-badge-stack .toolbarbutton-badge[value="0"] {
    display: none !important;
}`

**Comment by Keith94** [comment]
I used something similar too before I switched to Chrome.

**Comment by Peuj** [comment]
I've released a new version with the `Show badge if no duplicate tab` option.
If set to `false` (`true `by default to not change the behavior) it will not show badge value `0` if there is no duplicate tab.
You need to go to the full add-on options to access this option

**Comment by Keith94** [comment]
Thank you!

**Comment by Keith94** [comment]
Will Chrome version be updated soon?

**Comment by Peuj** [comment]
I just forgot. Thanks for the reminder :)

I've pushed the new version in Chrome, it should available in 1h max.
