### ISSUE TITLE
Ignore duplicate tabs on separate Firefox Tab Containers?

### ISSUE THREAD

**Issue by sprite-1** [Peuj/duplicate-tabs-closer#7]
Hi! First of all, thanks a lot for this great addon!

Would it be possible to have a setting that excludes tabs that are open on separate [Firefox Containers](https://support.mozilla.org/en-US/kb/containers)? I use it to manage multiple accounts on the same website/URL.

**Comment by Peuj** [comment]
With the option "Scope => Container" only duplicate tabs that belong to a same container are closed/displayed

![image](https://user-images.githubusercontent.com/6862131/49947281-210eed80-fef1-11e8-9c33-10813991eef0.png)

It's not what you need?

**Comment by sprite-1** [comment]
That is absolutely it! Thank you! For some reason, I thought that option means it will only work if I'm using a container and not include the default non-contained tabs.
